services:
  app:
    build:
      context: ./
      dockerfile: docker/php/DockerFile
    container_name: agro-app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./application:/var/www/application
    environment:
      - COMPOSER_HOME=/composer
      - COMPOSER_ALLOW_SUPERUSER=1
      - APP_ENV=local
      - APP_KEY=base64:rXAoY093ulFtVN2t3jftPRtAhkb4/+J7cw9O2h/+7iA=
    depends_on:
      - db
  
  node:
    image: node:20
    container_name: agro-node
    working_dir: /var/www/application
    volumes:
      - ./application:/var/www/application
    command: sh -c "npm install && npx vite --host 0.0.0.0"
    ports:
      - "5173:5173"
    networks:
      - default
    depends_on:
      - app

  nginx:
    image: nginx:1.25.1-alpine-slim
    container_name: agro-nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./application:/var/www/application
      - ./docker/nginx:/etc/nginx/conf.d

  db:
    build:
      context: ./
      dockerfile: docker/db/DockerFile
    container_name: agro-db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: agro-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@agro.com
      PGADMIN_DEFAULT_PASSWORD: agro100
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "5050:80"
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  db:
  pgadmin: